#!/bin/bash
FILES="$CELLWORLD_DATA/world/hexa*"

folder="$CELLWORLD_DATA/world"

mkdir "$folder" -p

for file in $FILES
do
  name=$(basename -s ".world" $file)
  if [[ $name == *"vr"* ]]; then
    continue
  fi
  if [[ $name == *"mice"* ]]; then
    continue
  fi
  new_name="${name}_mice"
  echo "$name"
  cellworld_convert_to_mice -world "$name" | ./save_item world "$new_name"
done

cd "$folder"
git add --all
git commit --all --message "worlds updated"
git push
