#!/bin/bash
FILES="$CELLWORLD_DATA/world/hexa*"
folder="$CELLWORLD_DATA/paths"
path_type="$1"
mkdir "$folder" -p

for file in $FILES
do
  world_name=$(basename -s ".world" $file)
  echo "$world_name"
#  world=$(cw_get_item world $world_name)

  cellworld_create_paths -world $world_name -path_type $path_type | ./save_item paths $world_name $path_type &
done

cd "$folder"
git add --all
git commit --all --message "worlds updated"
git push


#  path_type="euclidean"
#  cellworld_create_paths -world $world_name -path_type $path_type | ./save_item paths $world_name $path_type &
#
#  path_type="manhattan"
#  cellworld_create_paths -world $world_name -path_type $path_type | ./save_item paths $world_name $path_type &
#
#  path_type="astar"
#  cellworld_create_paths -world $world_name -path_type $path_type | ./save_item paths $world_name $path_type &
