#!/bin/bash
FILES="$CELLWORLD_DATA/world/hexa*"

folder="$CELLWORLD_DATA/graph"

#mkdir "$folder" -p

for file in $FILES
do
  #echo "$file"
  world_name=$(basename -s ".world" $file)
  echo "$world_name"
  cellworld_create_navigability -world "$world_name" | ./save_item graph "$world_name" "navigability"
done

cd "$folder"
git add --all
git commit --all --message "worlds updated"
git push
